QSvgAnimatedProperty: fix unity-build in C++20 mode
The self-made lerp() function conflicts with std::lerp(), according to
GCC 14:

  qsvganimatedproperty.cpp: In function ‘QPointF pointInterpolator(QPointF, QPointF, qreal)’:
  qsvganimatedproperty.cpp:32:19: error: call of overloaded ‘lerp(qreal, qreal, qreal&)’ is ambiguous
   32 |     qreal x = lerp(v1.x(), v2.x(), t);
      |               ~~~~^~~~~~~~~~~~~~~~~~~
  cmath:3891:3: note: candidate: ‘_Float128 std::lerp(_Float128, _Float128, _Float128)’
 3891 |   lerp(_Float128 __x, _Float128 __y, _Float128 __z) noexcept
      |   ^~~~
  cmath:3883:3: note: candidate: ‘_Float64 std::lerp(_Float64, _Float64, _Float64)’
 3883 |   lerp(_Float64 __x, _Float64 __y, _Float64 __z) noexcept
      |   ^~~~
  cmath:3858:3: note: candidate: ‘constexpr long double std::lerp(long double, long double, long double)’
 3858 |   lerp(long double __a, long double __b, long double __t) noexcept
      |   ^~~~
  cmath:3854:3: note: candidate: ‘constexpr double std::lerp(double, double, double)’
 3854 |   lerp(double __a, double __b, double __t) noexcept
      |   ^~~~
  cmath:3850:3: note: candidate: ‘constexpr float std::lerp(float, float, float)’
 3850 |   lerp(float __a, float __b, float __t) noexcept
      |   ^~~~
  qsvganimatedproperty.cpp:25:14: note: candidate: ‘qreal lerp(qreal, qreal, qreal)’
   25 | static qreal lerp(qreal a, qreal b, qreal t)
      |              ^~~~

Maybe some TU is using namespace std (didn't check).

Fix by renaming our lerp() to q_lerp().

Amends 36a315d9cf3cafb62332dd00c3d17d0f2a096d90.

Pick-to: 6.9
Change-Id: Ic3465b5b42bf7b86080d8952091b626643908978
Reviewed-by: Hatem ElKharashy <hatem.elkharashy@qt.io>